### ISSUE TITLE
Plugin is incompatible to Capacitor 6.0

### ISSUE THREAD

**Issue by tiga05** [glassfy/capacitor-plugin-glassfy#33]
Hi,

please upgrade your plugin to be compatible to Capacitor 6.0:

https://capacitorjs.com/docs/updating/plugins/6-0

**Comment by giovannigarifo** [comment]
Is there an ETA for the update?

**Comment by superm123** [comment]
Done

**Comment by superm123** [comment]
Please just make quick. Or give me a username. Cant really keep it public

**Comment by milkmusket** [comment]
@paologlassfy will you guys be continuing to support these plugins? I have been a bit worried about things since you announced no more paid plans. Also reached out to support about one issue and have not gotten anything back for 6 days when the estimated time was 2 days?

I would have been happy to pay for monthly as we grew, and I'd rather not migrate elsewhere, but worried about future updates. Hope you guys are well!

**Comment by marcopifferi** [comment]
hello, we planning to release support for capacitor 6 at the end of the month.
